import type { ToolDefinition } from './types.js';

/**
 * Forces reprocessing. Both actions are idempotent and rely on the background loops to refill:
 *  - vectors: empties the vector index → the backfill re-vectorizes every doc.
 *  - digests: deletes all digest+insight docs → the digest loop re-compresses every session.
 * Useful after bumping a version marker, or to test the phase-1 rollback path.
 */
const memoryReindex: ToolDefinition = {
  name: 'memory_reindex',
  description:
    'Forces reprocessing of existing memories. `vectors` empties the vector index (backfill refills it). `digests` deletes all LLM digests/insights (the digest loop regenerates them). With no argument, does both. Background, non-blocking; BM25 stays available throughout.',
  inputSchema: {
    type: 'object',
    properties: {
      vectors: { type: 'boolean', description: 'Clear and rebuild the vector index. Default: true if neither given.' },
      digests: { type: 'boolean', description: 'Delete and regenerate LLM digests/insights. Default: true if neither given.' },
    },
    additionalProperties: false,
  },
  handler: async (args, { store }) => {
    const both = args.vectors === undefined && args.digests === undefined;
    const doVectors = both || args.vectors === true;
    const doDigests = both || args.digests === true;
    const lines: string[] = ['**memory — reindex**'];

    if (doDigests) {
      const n = store.clearDigests();
      lines.push(`- Digests/insights: deleted **${n}** doc(s) → will be regenerated by the digest loop.`);
    }
    if (doVectors) {
      if (store.vectorEnabled) {
        store.resetVectors();
        lines.push('- Vectors: index emptied → will be refilled by the backfill.');
      } else {
        lines.push('- Vectors: index disabled (nothing to do).');
      }
    }
    lines.push('_Reprocessing runs in the background (non-blocking). BM25 stays available meanwhile._');
    return lines.join('\n');
  },
};

export const reindexTools: ToolDefinition[] = [memoryReindex];
